

fhand.write(r"\documentclass[a4paper, 9pt]{article}" + "\n")
fhand.write(r"\usepackage[utf8]{inputenc}" + "\n")
fhand.write(r"\usepackage[left=1.75cm, right=2.5cm, top=1.25cm, bottom=2.5cm]{geometry}" + "\n")
fhand.write(r"\usepackage{enumitem}" + "\n")
fhand.write(r"" + "\n")
fhand.write(r"\usepackage{tgheros}" + "\n")
fhand.write(r"\renewcommand*\familydefault{\sfdefault} %% Only if the base font of the document is to be sans serif" + "\n")
fhand.write(r"\usepackage[T1]{fontenc}" + "\n")
fhand.write(r"" + "\n")
fhand.write(r"" + "\n")
fhand.write(r"\usepackage{titlesec}" + "\n")
fhand.write(r"\titlespacing*{\section}{0pt}{0.3\baselineskip}{0.3\baselineskip}" + "\n")
fhand.write(r"\titlespacing*{\subsection}{0pt}{0.3\baselineskip}{0.2\baselineskip}" + "\n")
fhand.write(r"\titlespacing*{\subsubsection}{0pt}{0.3\baselineskip}{0.1\baselineskip}" + "\n")
fhand.write(r"" + "\n")
fhand.write(r"\usepackage{fancyhdr}" + "\n")
fhand.write(r"\fancyhf{}" + "\n")
fhand.write(r"\fancyfoot[L]{\scriptsize According to law 679/2016 of the Regulation of the European Parliament of 27th April 2016, I hereby express my consent to process and use my data provided in this CV and application for recruiting purposes}" + "\n")
fhand.write(r"\renewcommand\headrulewidth{0pt}" + "\n")
fhand.write(r"\pagestyle{fancy}" + "\n")
fhand.write(r"" + "\n")
fhand.write(r"" + "\n")
fhand.write(r"\title{Curriculum Vitae}" + "\n")
fhand.write(r"\author{" + name + surname "}" + "\n")
fhand.write(r"\date{\today}" + "\n")
fhand.write(r"" + "\n")
fhand.write(r"" + "\n")
fhand.write(r"\begin{document}" + "\n")
fhand.write(r"\section*{" + name + surname "}" + "\n")
fhand.write(r"" + "\n")
fhand.write(r"\small " + location + " -- Contacts: \textbf{" + e_mail "} -- " + pnumber +  " --" + "\n")
fhand.write(r"" + "\n")
fhand.write(r"" + "\n")
fhand.write(r"\section*{Summary}" + "\n")
fhand.write(r"SUMMARY!!!!!." + "\n")
fhand.write(r"" + "\n")
fhand.write(r"" + "\n")
fhand.write(r"\section*{Education}" + "\n")
fhand.write(r"\begin{itemize}[noitemsep]" + "\n")
fhand.write(r"\item EDU 1!!!!." + "\n")
fhand.write(r"\item EDU 2!!!!." + "\n")
fhand.write(r"\end{itemize}" + "\n")
fhand.write(r"" + "\n")
fhand.write(r"" + "\n")
fhand.write(r"\section*{Experience}" + "\n")
fhand.write(r"" + "\n")
fhand.write(r"\subsection*{EXP1 TITLE!!!!!}" + "\n")
fhand.write(r"\subsubsection*{EXP1 DATES!!!!!}" + "\n")
fhand.write(r"" + "\n")
fhand.write(r"\begin{itemize}[noitemsep]" + "\n")
fhand.write(r"" + "\n")
fhand.write(r"\item EXP1 BULLET 01!!!!." + "\n")
fhand.write(r"\item EXP1 BULLET 02!!!!." + "\n")
fhand.write(r"\end{itemize}" + "\n")
fhand.write(r"" + "\n")
fhand.write(r"\subsection*{EXP2 TITLE!!!!!}" + "\n")
fhand.write(r"\subsubsection*{EXP2 DATES!!!!!}" + "\n")
fhand.write(r"\begin{itemize}[noitemsep]" + "\n")
fhand.write(r"\item EXP2 BULLET 01!!!!." + "\n")
fhand.write(r"\item EXP2 BULLET 02!!!!." + "\n")
fhand.write(r"\end{itemize}" + "\n")
fhand.write(r"" + "\n")
fhand.write(r"\subsection*{}" + "\n")
fhand.write(r"\subsection*{Skills}" + "\n")
fhand.write(r"" + "\n")
fhand.write(r"\textbf {Languages}:\small LENGUAGES!!!." + "\n")
fhand.write(r"" + "\n")
fhand.write(r"\noindent \textbf{Software}:\small SOFTWARE!!!." + "\n")
fhand.write(r"" + "\n")
fhand.write(r"\noindent \textbf{Hard Skills}:\small HARD SKILLS!!!!." + "\n")
fhand.write(r"" + "\n")
fhand.write(r"\noindent \textbf{Soft skills}:\small SOFT SKILLS!!!." + "\n")
fhand.write(r"" + "\n")
fhand.write(r"\noindent \textbf{Field of Interest}:\small FIELD OF INTEREST!!!!." + "\n")
fhand.write(r"" + "\n")
fhand.write(r"\end{document}" + "\n")
