fhand.write("\documentclass[a4paper, 9pt]{article}\n)
fhand.write("\usepackage[utf8]{inputenc}\n)
fhand.write("\usepackage[left=1.75cm, right=2.5cm, top=1.25cm, bottom=2.5cm]{geometry}\n)
fhand.write("\usepackage{enumitem}\n)
fhand.write("\n)
fhand.write("\usepackage{tgheros}\n)
fhand.write("\renewcommand*\familydefault{\sfdefault} %% Only if the base font of the document is to be sans serif\n)
fhand.write("\usepackage[T1]{fontenc}\n)
fhand.write("\n)
fhand.write("\n)
fhand.write("\usepackage{titlesec}\n)
fhand.write("\titlespacing*{\section}{0pt}{0.3\baselineskip}{0.3\baselineskip}\n)
fhand.write("\titlespacing*{\subsection}{0pt}{0.3\baselineskip}{0.2\baselineskip}\n)
fhand.write("\titlespacing*{\subsubsection}{0pt}{0.3\baselineskip}{0.1\baselineskip}\n)
fhand.write("\n)
fhand.write("\usepackage{fancyhdr}\n)
fhand.write("\fancyhf{}\n)
fhand.write("\fancyfoot[L]{\scriptsize According to law 679/2016 of the Regulation of the European Parliament of 27th April 2016, I hereby express my consent to process and use my data provided in this CV and application for recruiting purposes}\n)
fhand.write("\renewcommand\headrulewidth{0pt}\n)
fhand.write("\pagestyle{fancy}\n)
fhand.write("\n)
fhand.write("\n)
fhand.write("\title{Curriculum Vitae}\n)
fhand.write("\author{NAME AND SURNAME!!!!!!!!}\n)
fhand.write("\date{\today}\n)
fhand.write("\n)
fhand.write("\n)
fhand.write("\begin{document}\n)
fhand.write("\section*{NAME SURNAME AND TITLE!!!!!!}\n)
fhand.write("\n)
fhand.write("\small LOCATION!!!! -- Contacts: \textbf{MAIL!!!!!} -- CELL NUMBER!!!! --\n)
fhand.write("\n)
fhand.write("\n)
fhand.write("\section*{Summary}\n)
fhand.write("SUMMARY!!!!!.\n)
fhand.write("\n)
fhand.write("\n)
fhand.write("\section*{Education}\n)
fhand.write("\begin{itemize}[noitemsep]\n)
fhand.write("\item EDU 1!!!!.\n)
fhand.write("\item EDU 2!!!!.\n)
fhand.write("\end{itemize}\n)
fhand.write("\n)
fhand.write("\n)
fhand.write("\section*{Experience}\n)
fhand.write("\n)
fhand.write("\subsection*{EXP1 TITLE!!!!!}\n)
fhand.write("\subsubsection*{EXP1 DATES!!!!!}\n)
fhand.write("\n)
fhand.write("\begin{itemize}[noitemsep]\n)
fhand.write("\n)
fhand.write("\item EXP1 BULLET 01!!!!.\n)
fhand.write("\item EXP1 BULLET 02!!!!.\n)
fhand.write("\end{itemize}\n)
fhand.write("\n)
fhand.write("\subsection*{EXP2 TITLE!!!!!}\n)
fhand.write("\subsubsection*{EXP2 DATES!!!!!}\n)
fhand.write("\begin{itemize}[noitemsep]\n)
fhand.write("\item EXP2 BULLET 01!!!!.\n)
fhand.write("\item EXP2 BULLET 02!!!!.\n)
fhand.write("\end{itemize}\n)
fhand.write("\n)
fhand.write("\subsection*{}\n)
fhand.write("\subsection*{Skills}\n)
fhand.write("\n)
fhand.write("\textbf {Languages}:\small LENGUAGES!!!.\n)
fhand.write("\n)
fhand.write("\noindent \textbf{Software}:\small SOFTWARE!!!.\n)
fhand.write("\n)
fhand.write("\noindent \textbf{Hard Skills}:\small HARD SKILLS!!!!.\n)
fhand.write("\n)
fhand.write("\noindent \textbf{Soft skills}:\small SOFT SKILLS!!!.\n)
fhand.write("\n)
fhand.write("\noindent \textbf{Field of Interest}:\small FIELD OF INTEREST!!!!.\n)
fhand.write("\n)
fhand.write("\end{document}\n)
