fhand.write(r"\documentclass[a4paper, 9pt]{article}" + r"n")
fhand.write(r"\usepackage[utf8]{inputenc}" + r"n")
fhand.write(r"\usepackage[left=1.75cm, right=2.5cm, top=1.25cm, bottom=2.5cm]{geometry}" + r"n")
fhand.write(r"\usepackage{enumitem}" + r"n")
fhand.write(r"" + r"n")
fhand.write(r"\usepackage{tgheros}" + r"n")
fhand.write(r"\renewcommand*\familydefault{\sfdefault} %% Only if the base font of the document is to be sans serif" + r"n")
fhand.write(r"\usepackage[T1]{fontenc}" + r"n")
fhand.write(r"" + r"n")
fhand.write(r"" + r"n")
fhand.write(r"\usepackage{titlesec}" + r"n")
fhand.write(r"\titlespacing*{\section}{0pt}{0.3\baselineskip}{0.3\baselineskip}" + r"n")
fhand.write(r"\titlespacing*{\subsection}{0pt}{0.3\baselineskip}{0.2\baselineskip}" + r"n")
fhand.write(r"\titlespacing*{\subsubsection}{0pt}{0.3\baselineskip}{0.1\baselineskip}" + r"n")
fhand.write(r"" + r"n")
fhand.write(r"\usepackage{fancyhdr}" + r"n")
fhand.write(r"\fancyhf{}" + r"n")
fhand.write(r"\fancyfoot[L]{\scriptsize According to law 679/2016 of the Regulation of the European Parliament of 27th April 2016, I hereby express my consent to process and use my data provided in this CV and application for recruiting purposes}" + r"n")
fhand.write(r"\renewcommand\headrulewidth{0pt}" + r"n")
fhand.write(r"\pagestyle{fancy}" + r"n")
fhand.write(r"" + r"n")
fhand.write(r"" + r"n")
fhand.write(r"\title{Curriculum Vitae}" + r"n")
fhand.write(r"\author{NAME AND SURNAME!!!!!!!!}" + r"n")
fhand.write(r"\date{\today}" + r"n")
fhand.write(r"" + r"n")
fhand.write(r"" + r"n")
fhand.write(r"\begin{document}" + r"n")
fhand.write(r"\section*{NAME SURNAME AND TITLE!!!!!!}" + r"n")
fhand.write(r"" + r"n")
fhand.write(r"\small LOCATION!!!! -- Contacts: \textbf{MAIL!!!!!} -- CELL NUMBER!!!! --" + r"n")
fhand.write(r"" + r"n")
fhand.write(r"" + r"n")
fhand.write(r"\section*{Summary}" + r"n")
fhand.write(r"SUMMARY!!!!!." + r"n")
fhand.write(r"" + r"n")
fhand.write(r"" + r"n")
fhand.write(r"\section*{Education}" + r"n")
fhand.write(r"\begin{itemize}[noitemsep]" + r"n")
fhand.write(r"\item EDU 1!!!!." + r"n")
fhand.write(r"\item EDU 2!!!!." + r"n")
fhand.write(r"\end{itemize}" + r"n")
fhand.write(r"" + r"n")
fhand.write(r"" + r"n")
fhand.write(r"\section*{Experience}" + r"n")
fhand.write(r"" + r"n")
fhand.write(r"\subsection*{EXP1 TITLE!!!!!}" + r"n")
fhand.write(r"\subsubsection*{EXP1 DATES!!!!!}" + r"n")
fhand.write(r"" + r"n")
fhand.write(r"\begin{itemize}[noitemsep]" + r"n")
fhand.write(r"" + r"n")
fhand.write(r"\item EXP1 BULLET 01!!!!." + r"n")
fhand.write(r"\item EXP1 BULLET 02!!!!." + r"n")
fhand.write(r"\end{itemize}" + r"n")
fhand.write(r"" + r"n")
fhand.write(r"\subsection*{EXP2 TITLE!!!!!}" + r"n")
fhand.write(r"\subsubsection*{EXP2 DATES!!!!!}" + r"n")
fhand.write(r"\begin{itemize}[noitemsep]" + r"n")
fhand.write(r"\item EXP2 BULLET 01!!!!." + r"n")
fhand.write(r"\item EXP2 BULLET 02!!!!." + r"n")
fhand.write(r"\end{itemize}" + r"n")
fhand.write(r"" + r"n")
fhand.write(r"\subsection*{}" + r"n")
fhand.write(r"\subsection*{Skills}" + r"n")
fhand.write(r"" + r"n")
fhand.write(r"\textbf {Languages}:\small LENGUAGES!!!." + r"n")
fhand.write(r"" + r"n")
fhand.write(r"\noindent \textbf{Software}:\small SOFTWARE!!!." + r"n")
fhand.write(r"" + r"n")
fhand.write(r"\noindent \textbf{Hard Skills}:\small HARD SKILLS!!!!." + r"n")
fhand.write(r"" + r"n")
fhand.write(r"\noindent \textbf{Soft skills}:\small SOFT SKILLS!!!." + r"n")
fhand.write(r"" + r"n")
fhand.write(r"\noindent \textbf{Field of Interest}:\small FIELD OF INTEREST!!!!." + r"n")
fhand.write(r"" + r"n")
fhand.write(r"\end{document}" + r"n")
